services:
  - type: web
    name: api-corner
    env: node
    plan: free
    buildCommand: npm install && npm install --prefix Client --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true # Render will automatically generate a secure random secret key
      - key: MONGODB_URI
        sync: false # Render will prompt you to enter your MongoDB Atlas URI during setup
